// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"encoding/json"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"order-service-rest-api/config"
	order2 "order-service-rest-api/internal/api/order"
	"order-service-rest-api/internal/app/orders"
	"order-service-rest-api/internal/common/errors"
	"order-service-rest-api/internal/infrastructure/adapter/productserv"
	"order-service-rest-api/internal/infrastructure/adapter/userserv"
	"order-service-rest-api/internal/infrastructure/persistence/db"
	"order-service-rest-api/internal/infrastructure/persistence/order"
	"order-service-rest-api/internal/message"
	"order-service-rest-api/internal/middleware"
	"order-service-rest-api/internal/middleware/auth"
	"order-service-rest-api/internal/router"
)

// Injectors from server.go:

func New() (*Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	gorm := db.NewMySQLConnection(configConfig)
	repository := order.NewGormRepository(gorm)
	service := productserv.NewProductServAdapter(configConfig)
	usecase := orders.NewOrderService(repository, service)
	orderApiHandler := order2.NewOrderHandler(usecase)
	userservService := userserv.NewUserServHttpAdapter(configConfig)
	authenticationMiddleware := auth.NewAuthMiddleware(userservService)
	middlewareMiddleware := middleware.NewMiddleware(authenticationMiddleware)
	orderRouter := router.NewOrderRouter(orderApiHandler, middlewareMiddleware)
	consumerOrderMessage := message.NewConsumerOrderMessage(configConfig, repository, usecase)
	server := NewServer(configConfig, orderRouter, consumerOrderMessage)
	return server, nil
}

// server.go:

type Server struct {
	app      *fiber.App
	cfg      *config.Config
	consumer *message.ConsumerOrderMessage
}

func NewServer(
	cfg *config.Config,
	orderRouter router.OrderRouter,
	consumer *message.ConsumerOrderMessage) *Server {

	app := fiber.New(fiber.Config{
		ReadTimeout:  cfg.Server.ReadTimeout,
		WriteTimeout: cfg.Server.WriteTimeout,
		JSONDecoder:  json.Unmarshal,
		JSONEncoder:  json.Marshal,
		ErrorHandler: errors.CustomErrorHandler,
	})

	app.Use(logger.New())

	app.Get("", func(ctx *fiber.Ctx) error {
		return ctx.JSON("Orders service developed by Tien Dat")
	})

	api := app.Group("/api")
	v1 := api.Group("/v1")

	orderRouter.Init(&v1)

	return &Server{
		cfg:      cfg,
		app:      app,
		consumer: consumer,
	}
}

func (serv Server) App() *fiber.App {
	return serv.app
}

func (serv Server) Config() *config.Config {
	return serv.cfg
}

func (serv Server) Consumer() *message.ConsumerOrderMessage {
	return serv.consumer
}
