# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    # order-rest-api
    - name: Build rest-service
      run: cd order-rest-api && go build -v ./...

    - name: Test rest-service
      run: cd order-rest-api && go test -v ./...

   # order-worker
    - name: Build worker
      run: cd order-worker && go build -v ./...

    - name: Test rest-service
      run: cd order-worker && go test -v ./...
